Coursera course: Data Science with Real world data in Pharma
Date: May 07, 2026

Prepare the data for the analysis
The data we are going to use for this course was generated using Synthea, a tool that generates synthetic patient data. From the data generated by Synthea, 
we extracted the information for patients with prostate cancer only and copied only the relevant files into data_prostate/parquet. You can learn more about 
how this preparation step was done in data_generation/reproduce_data_generation.txt.

You can learn more about Synthea in their webpage. Of particular relevance for this section is the data dictionary where there is a relation of files and 
the meaning of each column on them, and the prostate cancer module that explains the patient journey.

In this notebook, we are going to extract the data we need for our analysis and derive new variables as needed. As a first step, we load the packages we need and define where the data is located

import os 

import pandas as pd 
import numpy as np

# where to find the data in parquet format
data_folder = "~/work/data/parquet"

Get the diagnoses dates and disease progression.
All patients have an initial neoplasm diagnosis. After that, the patients are diagnosed with either carcinoma in situ (localized) or metastatic carcinoma (the cancer has spread to other locations). 
Later on, some patients with carcinoma in situ may progress to a metastatic carcinoma. Let's collect the dates for these diagnoses and the disease progression for each patient.

For this task, we need to look at is "conditions". As you can see below, this file contains an identifier for each patient, the code and the description for the situation or diagnosis (disease), 
an identifier for the encounter (patient visiting the doctor) and a date for the start and stop of that encounter.

# we can read the data with the method read_parquet (as the data is stored in parquet format)
# os.path.join will simply concatenate the path to the data (data_folder) and the filename of the file we want to open
conditions = pd.read_parquet(os.path.join(data_folder, "conditions.parquet"))
conditions.head()

# Here we have the medical codes corresponding to the three diagnosis of interest
prostate_codes = [126906006, # Neoplasm of prostate
                92691004, # Carcinoma in situ of prostate (disorder)
                314994000, # Metastasis from malignant tumor of prostate (disorder)
                  ]
# We filter the conditions dataframe to keep only the rows corresponding to the prostate conditions
prostate_conditions = conditions.loc[conditions["code"].isin(prostate_codes), ["patient", "description", "start", ]]
# convert start to a pandas datetime for it to be easier to manipulate later. We introduce UTC timezone as other columns will be in UTC
prostate_conditions["start"] = pd.to_datetime(prostate_conditions["start"], utc=True)
prostate_conditions.head()

As you see we have the data in long format, and what we would like to have is in wide format, i.e. one column for each diagnosis containing the date of the diagnosis.
# pivot to have one column for each of neoplasm, in situ, metastatic. We use the pivot method
prostate_piv = prostate_conditions.pivot(index="patient", values="start", columns="description")
# rename the columns to be more informative, use the rename method and pass a dictionary with the labels
col_names = {'Carcinoma in situ of prostate (disorder)': 'carcinoma_in_situ_dx_date',
             'Metastasis from malignant tumor of prostate (disorder)': 'metastasis_dx_date',
             'Neoplasm of prostate': 'neoplasm_dx_date'}
prostate_piv = prostate_piv.rename(columns=col_names)
prostate_piv.head()

Let's finally build a variable to capture these progressions.
def assign_progression(df):
    """
    This functions gets a row of the dataframe and assigns a progression status
    based in the three diagnosis dates
    """
    # if there is metastatisis not carcinoma in situ
    if not pd.isna(df["metastasis_dx_date"]) and pd.isna(df["carcinoma_in_situ_dx_date"]):
        return "metastatic"
    # if there is carcinoma in situ but not metastasis
    elif not pd.isna(df["carcinoma_in_situ_dx_date"]) and pd.isna(df["metastasis_dx_date"]):
        return "in situ"
    # else it means it started with in situ and progressed to metastatic
    else:
        return "in situ -> metastatic"
# apply the function to the dataframe and save it in a variable "progression"
prostate_piv["progression"] = prostate_piv.apply(assign_progression, axis=1)
# let's see the counts
prostate_piv["progression"].value_counts()

Medications
Patients may receive one or two rounds of medication. We would like to know how many rounds of medications the patients got and the start of each round.
For this purpose we need the medications file. Here there are recorded all medications given to the patients for all purposes. We filter for medications given for prostate cancer only and extract a few columns we need.
We then take a look at what is the count of medications. As you can see there are two medications with exactly the same counts: Leuprolide Acetate (an hormonal supressing therapy) 
and Docetaxel (chemotherapy), and there are no other medications given to the patients.

# read the medications file
medications = pd.read_parquet(os.path.join(data_folder, "medications.parquet"))
# filter the medications and keep only the ones related to prostate cancer
prostate_medications = medications.loc[medications["reasondescription"]=="Neoplasm of prostate", ["patient", "description", "start"]]
prostate_medications.groupby("description").size()

Taking a look to the data, we notice that these two drugs are given at exactly the same time.
prostate_medications.head(6)

As the two drugs are given always in combination, we will consider them as one treatment and we will keep the date for only one of them, 
and then calculate the dates for the different rounds of medications, which we will call "lines of treatment". We can see that patients may have one or two lines of treatment.

# get a single line per patient and the start date of the line and sort by start date
lines = prostate_medications[["patient", "start"]].drop_duplicates().sort_values(by="start")
# create a variable with the number of the medication round (medication line)
lines['line_number'] = lines.groupby('patient').cumcount()+1
# pivot by the medication line
lines_piv = lines.pivot(index="patient", columns="line_number", values="start").reset_index()
# rename the columns to be more informative
lines_piv = lines_piv.rename(columns={1: "line_1_start", 2: "line_2_start",})
# build a column indication werther the patient received one or two lines of treatment
lines_piv["lines_of_treatment"] = np.where(pd.isna(lines_piv["line_2_start"]), "L1", "L2")
lines_piv.head()

Output:
line_number	patient	line_1_start	line_2_start	lines_of_treatment
0	00b99a22-6749-4c13-b0f8-5d3957263377	2023-01-06 08:25:13+00:00	NaT	L1
1	00c9fc77-8956-e9f2-9637-ec1384e5e4f0	2023-08-14 06:51:32+00:00	2023-11-12 11:20:32+00:00	L2
2	00d0790e-25c5-25b8-b021-2a51dde140a0	2017-06-12 09:40:53+00:00	2017-09-10 14:33:53+00:00	L2
3	00ea3106-3410-65aa-5e07-84ee326e3432	2018-09-15 19:29:26+00:00	2018-12-15 00:56:26+00:00	L2
4	00f6f5e6-7f25-587e-1551-ee423dd0f22d	2018-01-07 00:52:36+00:00	2018-04-07 05:18:36+00:00	L2

Demographics
We next get demographics patient data from the patients file.










